version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1005
        - -ST1020
        - -ST1021
        - -ST1022
        - -SA1019
        - -QF1003

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - agent-collab

issues:
  exclude-use-default: false
